//! Max scoring for disjunctions, ported from
//! `org.apache.lucene.search.DisjunctionMaxScorer`.

#![deny(unsafe_code)]

use crate::error::{LuceneError, Result};
use crate::search::disjunction_score_block_boundary_propagator::DisjunctionScoreBlockBoundaryPropagator;
use crate::search::disjunction_scorer::DisjunctionScorer;
use crate::search::doc_id_set_iterator::{DocIdSetIterator, NO_MORE_DOCS};
use crate::search::scorable::{ChildScorable, Scorable};
use crate::search::score_mode::ScoreMode;
use crate::search::scorer::Scorer;
use crate::search::two_phase_iterator::TwoPhaseIterator;
use crate::util::MathUtil;

/// The scorer for [`DisjunctionMaxQuery`](crate::search::DisjunctionMaxQuery).
///
/// Equivalent to the `final class
/// org.apache.lucene.search.DisjunctionMaxScorer`. The union of all documents
/// generated by the subquery scorers is generated in document number order. The
/// score for each document is the maximum of the scores computed by the
/// subquery scorers that generate that document, plus `tie_breaker_multiplier`
/// times the sum of the scores for the other subqueries that generate the
/// document.
#[derive(Debug)]
pub struct DisjunctionMaxScorer {
    base: DisjunctionScorer,
    /// Multiplier applied to non-maximum-scoring subqueries for a document as
    /// they are summed into the result.
    tie_breaker_multiplier: f32,
    disjunction_block_propagator: Option<DisjunctionScoreBlockBoundaryPropagator>,
}

impl DisjunctionMaxScorer {
    /// Creates a new instance.
    ///
    /// Equivalent to `DisjunctionMaxScorer(float, List<Scorer>, ScoreMode,
    /// long)`.
    ///
    /// # Errors
    ///
    /// Returns [`LuceneError::IllegalArgument`] when `tie_breaker_multiplier`
    /// is outside `[0, 1]`, and propagates the errors of
    /// [`DisjunctionScorer::new`] and of the block-boundary propagator.
    pub fn new(
        tie_breaker_multiplier: f32,
        sub_scorers: Vec<Box<dyn Scorer>>,
        score_mode: ScoreMode,
        lead_cost: i64,
    ) -> Result<Self> {
        let mut base = DisjunctionScorer::new(sub_scorers, score_mode, lead_cost)?;
        if !(0.0..=1.0).contains(&tie_breaker_multiplier) {
            return Err(LuceneError::IllegalArgument(
                "tieBreakerMultiplier must be in [0, 1]".to_string(),
            ));
        }
        let disjunction_block_propagator = if score_mode == ScoreMode::TOP_SCORES {
            Some(DisjunctionScoreBlockBoundaryPropagator::new(&mut base)?)
        } else {
            None
        };
        Ok(Self {
            base,
            tie_breaker_multiplier,
            disjunction_block_propagator,
        })
    }
}

impl DocIdSetIterator for DisjunctionMaxScorer {
    fn doc_id(&self) -> i32 {
        self.base.doc_id()
    }

    fn next_doc(&mut self) -> Result<i32> {
        self.base.next_doc()
    }

    fn advance(&mut self, target: i32) -> Result<i32> {
        self.base.advance(target)
    }

    fn cost(&self) -> i64 {
        self.base.cost()
    }
}

impl Scorable for DisjunctionMaxScorer {
    fn score(&mut self) -> Result<f32> {
        let mut score_max = 0.0f32;
        let mut other_score_sum = 0.0f64;
        for position in self.base.sub_matches()? {
            let sub_score = self.base.wrapper(position).scorable().score()?;
            if sub_score >= score_max {
                other_score_sum += f64::from(score_max);
                score_max = sub_score;
            } else {
                other_score_sum += f64::from(sub_score);
            }
        }
        Ok((f64::from(score_max) + other_score_sum * f64::from(self.tie_breaker_multiplier)) as f32)
    }

    fn set_min_competitive_score(&mut self, min_score: f32) -> Result<()> {
        if let Some(propagator) = self.disjunction_block_propagator.as_mut() {
            propagator.set_min_competitive_score(min_score);
        }
        if self.tie_breaker_multiplier == 0.0 {
            // TODO(lucene): we could even remove some scorers from the priority
            // queue?
            for i in 0..self.base.num_clauses() {
                self.base
                    .approximation()
                    .sub_scorer(i)
                    .scorer()
                    .set_min_competitive_score(min_score)?;
            }
        }
        Ok(())
    }

    fn children(&mut self) -> Result<Vec<ChildScorable<'_>>> {
        self.base.children()
    }
}

impl Scorer for DisjunctionMaxScorer {
    fn as_scorable(&mut self) -> &mut dyn Scorable {
        self
    }

    fn doc_id(&self) -> i32 {
        self.base.doc_id()
    }

    fn iterator(&mut self) -> &mut dyn DocIdSetIterator {
        self
    }

    fn two_phase_iterator(&mut self) -> Option<&mut dyn TwoPhaseIterator> {
        if self.base.has_two_phase() {
            Some(&mut self.base)
        } else {
            None
        }
    }

    fn advance_shallow(&mut self, target: i32) -> Result<i32> {
        match self.disjunction_block_propagator.as_mut() {
            Some(propagator) => propagator.advance_shallow(&mut self.base, target),
            // `super.advanceShallow(int)` is `Scorer`'s default.
            None => Ok(NO_MORE_DOCS),
        }
    }

    fn get_max_score(&mut self, up_to: i32) -> Result<f32> {
        let num_clauses = self.base.num_clauses();
        let mut score_max = 0.0f32;
        let mut other_score_sum = 0.0f64;
        for i in 0..num_clauses {
            let scorer = self.base.approximation().sub_scorer(i).scorer();
            if Scorer::doc_id(scorer) <= up_to {
                let sub_score = scorer.get_max_score(up_to)?;
                if sub_score >= score_max {
                    other_score_sum += f64::from(score_max);
                    score_max = sub_score;
                } else {
                    other_score_sum += f64::from(sub_score);
                }
            }
        }

        if self.tie_breaker_multiplier == 0.0 {
            Ok(score_max)
        } else {
            // The error of sums depends on the order in which values are summed
            // up. In order to avoid this issue, we compute an upper bound of the
            // value that the sum may take. If the max relative error is b, then
            // it means that two sums are always within 2*b of each other.
            other_score_sum *= 1.0 + 2.0 * MathUtil::sum_relative_error_bound(num_clauses as i32 - 1);
            Ok(
                (f64::from(score_max) + other_score_sum * f64::from(self.tie_breaker_multiplier))
                    as f32,
            )
        }
    }
}
