//! The language-modelling similarities, ported from
//! `org.apache.lucene.search.similarities.LMSimilarity` and its three
//! descendants.
//!
//! `LMSimilarity` introduces three types beyond the ranking models themselves:
//! [`LMStats`], which adds the probability that the collection language model
//! generates the current term; [`CollectionModel`], the strategy that computes
//! `p(w|C)`; and [`DefaultCollectionModel`], the implementation that divides
//! the term's collection frequency by the total token count.

#![deny(unsafe_code)]

use std::borrow::{Borrow, BorrowMut};
use std::fmt::{self, Debug};
use std::ops::Deref;

use crate::error::{LuceneError, Result};

use super::similarity_base::{fill_basic_stats, similarity_base_scorer};
use super::{java_fmt, BasicStats, CollectionStatistics, Explanation};
use super::{SimScorer, Similarity, SimilarityBase, TermStatistics};

// ---------------------------------------------------------------------------
// LMStats
// ---------------------------------------------------------------------------

/// Stores the collection distribution of the current term.
///
/// Equivalent to the nested `LMSimilarity.LMStats`
/// (`LMSimilarity.java:107-121`), which extends `BasicStats`. Rust has no
/// inheritance, so the base statistics are held as a field and reached through
/// [`Deref`]; that is what lets the formulas below read `stats.boost()` exactly
/// as their Java counterparts do, and what replaces the
/// `(LMStats) stats` downcasts Lucene performs.
#[derive(Debug, Clone, PartialEq)]
pub struct LMStats {
    base: BasicStats,
    collection_probability: f64,
}

impl LMStats {
    /// Creates `LMStats` for the provided field and query-time boost.
    ///
    /// Equivalent to `new LMSimilarity.LMStats(String, double)`
    /// (`LMSimilarity.java:112-114`).
    pub fn new(field: impl Into<String>, boost: f64) -> Self {
        Self {
            base: BasicStats::new(field, boost),
            collection_probability: 0.0,
        }
    }

    /// Returns the probability that the current term is generated by the
    /// collection.
    ///
    /// Equivalent to `LMStats.getCollectionProbability()`.
    pub fn collection_probability(&self) -> f64 {
        self.collection_probability
    }

    /// Sets the probability that the current term is generated by the
    /// collection.
    ///
    /// Equivalent to `LMStats.setCollectionProbability(double)`.
    pub fn set_collection_probability(&mut self, collection_probability: f64) {
        self.collection_probability = collection_probability;
    }
}

impl From<BasicStats> for LMStats {
    fn from(base: BasicStats) -> Self {
        Self {
            base,
            collection_probability: 0.0,
        }
    }
}

impl Deref for LMStats {
    type Target = BasicStats;

    fn deref(&self) -> &BasicStats {
        &self.base
    }
}

impl Borrow<BasicStats> for LMStats {
    fn borrow(&self) -> &BasicStats {
        &self.base
    }
}

impl BorrowMut<BasicStats> for LMStats {
    fn borrow_mut(&mut self) -> &mut BasicStats {
        &mut self.base
    }
}

// ---------------------------------------------------------------------------
// CollectionModel
// ---------------------------------------------------------------------------

/// A strategy for computing the collection language model.
///
/// Equivalent to the nested interface `LMSimilarity.CollectionModel`
/// (`LMSimilarity.java:124-133`).
pub trait CollectionModel: Debug + Send + Sync {
    /// Computes the probability `p(w|C)` for the current term.
    ///
    /// Equivalent to `CollectionModel.computeProbability(BasicStats)`.
    fn compute_probability(&self, stats: &BasicStats) -> f64;

    /// Returns the name of the collection-model strategy.
    ///
    /// Equivalent to `CollectionModel.getName()`, which returns `null` for the
    /// two models Lucene ships; `None` carries that here, and
    /// [`lm_to_string`] omits the suffix for it.
    fn name(&self) -> Option<String>;
}

/// Models `p(w|C)` as the number of occurrences of the term in the collection,
/// divided by the total number of tokens `+ 1`.
///
/// Equivalent to the nested `LMSimilarity.DefaultCollectionModel`
/// (`LMSimilarity.java:139-153`).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DefaultCollectionModel;

impl DefaultCollectionModel {
    /// Creates the parameter-free collection model.
    ///
    /// Equivalent to `new LMSimilarity.DefaultCollectionModel()`.
    pub fn new() -> Self {
        Self
    }
}

impl CollectionModel for DefaultCollectionModel {
    fn compute_probability(&self, stats: &BasicStats) -> f64 {
        (stats.total_term_freq() as f64 + 1.0) / (stats.number_of_field_tokens() as f64 + 1.0)
    }

    fn name(&self) -> Option<String> {
        None
    }
}

// ---------------------------------------------------------------------------
// LMSimilarity
// ---------------------------------------------------------------------------

/// Superclass for language-modelling similarities.
///
/// Equivalent to `org.apache.lucene.search.similarities.LMSimilarity`. Java
/// overrides `newStats`, `fillBasicStats`, `explain(List, …)` and `toString()`
/// here and inherits them into the three concrete models; a Rust subtrait
/// cannot override a supertrait's methods, so the shared bodies are the free
/// functions [`lm_new_stats`], [`lm_fill_basic_stats`], [`lm_explain_details`]
/// and [`lm_to_string`], and each concrete model forwards to them in one line.
pub trait LMSimilarity: SimilarityBase<Stats = LMStats> {
    /// Returns the collection model this similarity smooths with.
    ///
    /// Java holds it in the `protected final collectionModel` field
    /// (`LMSimilarity.java:38`).
    fn collection_model(&self) -> &dyn CollectionModel;

    /// Returns the name of the LM method, parameter values included.
    ///
    /// Equivalent to the abstract `LMSimilarity.getName()`
    /// (`LMSimilarity.java:79`). Used by [`lm_to_string`].
    fn name(&self) -> String;
}

/// Creates the statistics object the language-modelling family scores from.
///
/// This is the body of `LMSimilarity.newStats` (`LMSimilarity.java:47-49`).
pub fn lm_new_stats(field: &str, boost: f64) -> LMStats {
    LMStats::new(field, boost)
}

/// Computes the collection probability of the current term in addition to the
/// usual statistics.
///
/// This is the body of `LMSimilarity.fillBasicStats`
/// (`LMSimilarity.java:55-61`), including its `super.fillBasicStats` call.
pub fn lm_fill_basic_stats(
    collection_model: &dyn CollectionModel,
    stats: &mut LMStats,
    collection_stats: &CollectionStatistics,
    term_stats: &TermStatistics,
) {
    fill_basic_stats(&mut stats.base, collection_stats, term_stats);
    let probability = collection_model.compute_probability(&stats.base);
    stats.set_collection_probability(probability);
}

/// Adds the collection-probability node every language model reports.
///
/// This is the body of `LMSimilarity.explain(List, BasicStats, double, double)`
/// (`LMSimilarity.java:64-69`), which the three concrete models reach through
/// `super.explain` at the *end* of their own `explain`.
pub fn lm_explain_details(
    collection_model: &dyn CollectionModel,
    sub_expls: &mut Vec<Explanation>,
    stats: &LMStats,
) {
    sub_expls.push(Explanation::matched(
        collection_model.compute_probability(&stats.base) as f32,
        "collection probability",
        vec![],
    ));
}

/// Renders a language-modelling similarity.
///
/// This is the body of `LMSimilarity.toString()`
/// (`LMSimilarity.java:88-95`): the LM method's name, plus the collection
/// model's name when it has one.
pub fn lm_to_string(similarity: &dyn LMSimilarity) -> String {
    match similarity.collection_model().name() {
        Some(collection) => format!("LM {} - {}", similarity.name(), collection),
        None => format!("LM {}", similarity.name()),
    }
}

// ---------------------------------------------------------------------------
// LMDirichletSimilarity
// ---------------------------------------------------------------------------

/// Bayesian smoothing using Dirichlet priors.
///
/// Equivalent to `org.apache.lucene.search.similarities.LMDirichletSimilarity`.
/// From Chengxiang Zhai and John Lafferty, *A study of smoothing methods for
/// language models applied to Ad Hoc information retrieval*, SIGIR '01,
/// pp. 334-342.
///
/// The formula as defined in the paper assigns a negative score to documents
/// that contain the term but with fewer occurrences than the collection
/// language model predicts; Lucene returns `0` for such documents, and so does
/// this port.
#[derive(Debug)]
pub struct LMDirichletSimilarity {
    mu: f32,
    collection_model: Box<dyn CollectionModel>,
    discount_overlaps: bool,
}

impl LMDirichletSimilarity {
    /// Rejects a `mu` Java's constructors reject
    /// (`LMDirichletSimilarity.java:41-44`).
    fn check_mu(mu: f32) -> Result<()> {
        if !mu.is_finite() || mu < 0.0 {
            return Err(LuceneError::IllegalArgument(format!(
                "illegal mu value: {}, must be a non-negative finite value",
                java_fmt::float_to_string(mu)
            )));
        }
        Ok(())
    }

    /// Creates the similarity with the default `mu` of `2000` and the default
    /// collection model.
    ///
    /// Equivalent to `new LMDirichletSimilarity()`
    /// (`LMDirichletSimilarity.java:71-73`).
    pub fn new() -> Self {
        Self {
            mu: 2000.0,
            collection_model: Box::new(DefaultCollectionModel::new()),
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with the provided `mu` and the default collection
    /// model.
    ///
    /// Equivalent to `new LMDirichletSimilarity(float)`
    /// (`LMDirichletSimilarity.java:60-65`).
    ///
    /// # Errors
    ///
    /// Returns [`LuceneError::IllegalArgument`] when `mu` is not finite or is
    /// negative.
    pub fn with_mu(mu: f32) -> Result<Self> {
        Self::check_mu(mu)?;
        Ok(Self {
            mu,
            collection_model: Box::new(DefaultCollectionModel::new()),
            discount_overlaps: true,
        })
    }

    /// Creates the similarity with the provided collection model and the
    /// default `mu` of `2000`.
    ///
    /// Equivalent to `new LMDirichletSimilarity(CollectionModel)`
    /// (`LMDirichletSimilarity.java:67-69`).
    pub fn with_collection_model(collection_model: Box<dyn CollectionModel>) -> Self {
        Self {
            mu: 2000.0,
            collection_model,
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with the provided collection model and `mu`.
    ///
    /// Equivalent to `new LMDirichletSimilarity(CollectionModel, float)`
    /// (`LMDirichletSimilarity.java:35-37`).
    ///
    /// # Errors
    ///
    /// See [`Self::with_mu`].
    pub fn with_collection_model_and_mu(
        collection_model: Box<dyn CollectionModel>,
        mu: f32,
    ) -> Result<Self> {
        Self::with_parameters(collection_model, true, mu)
    }

    /// Creates the similarity with every parameter supplied.
    ///
    /// Equivalent to
    /// `new LMDirichletSimilarity(CollectionModel, boolean, float)`
    /// (`LMDirichletSimilarity.java:39-47`).
    ///
    /// # Errors
    ///
    /// See [`Self::with_mu`].
    pub fn with_parameters(
        collection_model: Box<dyn CollectionModel>,
        discount_overlaps: bool,
        mu: f32,
    ) -> Result<Self> {
        Self::check_mu(mu)?;
        Ok(Self {
            mu,
            collection_model,
            discount_overlaps,
        })
    }

    /// Returns the `mu` parameter.
    ///
    /// Equivalent to `LMDirichletSimilarity.getMu()`.
    pub fn mu(&self) -> f32 {
        self.mu
    }
}

impl Default for LMDirichletSimilarity {
    fn default() -> Self {
        Self::new()
    }
}

impl Similarity for LMDirichletSimilarity {
    fn discount_overlaps(&self) -> bool {
        self.discount_overlaps
    }

    fn scorer<'a>(
        &'a self,
        boost: f32,
        collection_stats: &CollectionStatistics,
        term_stats: &[TermStatistics],
    ) -> Box<dyn SimScorer + 'a> {
        similarity_base_scorer(self, boost, collection_stats, term_stats)
    }
}

impl SimilarityBase for LMDirichletSimilarity {
    type Stats = LMStats;

    fn simple_name(&self) -> &'static str {
        "LMDirichletSimilarity"
    }

    fn new_stats(&self, field: &str, boost: f64) -> LMStats {
        lm_new_stats(field, boost)
    }

    fn fill_basic_stats(
        &self,
        stats: &mut LMStats,
        collection_stats: &CollectionStatistics,
        term_stats: &TermStatistics,
    ) {
        lm_fill_basic_stats(
            self.collection_model.as_ref(),
            stats,
            collection_stats,
            term_stats,
        );
    }

    fn score(&self, stats: &LMStats, freq: f64, doc_len: f64) -> f64 {
        let mu = f64::from(self.mu);
        let score = stats.boost()
            * ((1.0 + freq / (mu * stats.collection_probability())).ln()
                + (mu / (doc_len + mu)).ln());
        if score > 0.0 {
            score
        } else {
            0.0
        }
    }

    fn explain_details(
        &self,
        subs: &mut Vec<Explanation>,
        stats: &LMStats,
        freq: f64,
        doc_len: f64,
    ) {
        if stats.boost() != 1.0 {
            subs.push(Explanation::matched(
                stats.boost() as f32,
                "query boost",
                vec![],
            ));
        }
        let mu = f64::from(self.mu);
        let p = stats.collection_probability();
        let expl_p = Explanation::matched(
            p as f32,
            "P, probability that the current term is generated by the collection",
            vec![],
        );
        let expl_freq = Explanation::matched(
            freq as f32,
            "freq, number of occurrences of term in the document",
            vec![],
        );

        subs.push(Explanation::matched(self.mu, "mu", vec![]));
        subs.push(Explanation::matched(
            (1.0 + freq / (mu * p)).ln() as f32,
            "term weight, computed as log(1 + freq /(mu * P)) from:",
            vec![expl_freq, expl_p],
        ));
        subs.push(Explanation::matched(
            (mu / (doc_len + mu)).ln() as f32,
            "document norm, computed as log(mu / (dl + mu))",
            vec![],
        ));
        subs.push(Explanation::matched(
            doc_len as f32,
            "dl, length of field",
            vec![],
        ));
        lm_explain_details(self.collection_model.as_ref(), subs, stats);
    }

    /// Overrides the base explanation, as
    /// `LMDirichletSimilarity.explain(BasicStats, Explanation, double)` does
    /// (`LMDirichletSimilarity.java:110-124`), taking the frequency as a
    /// `double`.
    fn explain(&self, stats: &LMStats, freq: &Explanation, doc_len: f64) -> Explanation {
        let mut subs = Vec::new();
        let freq_value = freq.value().double_value();
        self.explain_details(&mut subs, stats, freq_value, doc_len);

        Explanation::matched(
            self.score(stats, freq_value, doc_len) as f32,
            format!(
                "score({}, freq={}), computed as boost * (term weight + document norm) from:",
                self.simple_name(),
                freq.value()
            ),
            subs,
        )
    }
}

impl LMSimilarity for LMDirichletSimilarity {
    fn collection_model(&self) -> &dyn CollectionModel {
        self.collection_model.as_ref()
    }

    fn name(&self) -> String {
        format!("Dirichlet({})", java_fmt::format_f(f64::from(self.mu)))
    }
}

impl fmt::Display for LMDirichletSimilarity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&lm_to_string(self))
    }
}

// ---------------------------------------------------------------------------
// LMJelinekMercerSimilarity
// ---------------------------------------------------------------------------

/// Language model based on the Jelinek-Mercer smoothing method.
///
/// Equivalent to
/// `org.apache.lucene.search.similarities.LMJelinekMercerSimilarity`. From
/// Chengxiang Zhai and John Lafferty, *A study of smoothing methods for
/// language models applied to Ad Hoc information retrieval*, SIGIR '01,
/// pp. 334-342.
///
/// The model has a single parameter, *λ*. According to the paper its optimal
/// value depends on both the collection and the query, and is around `0.1` for
/// title queries and `0.7` for long ones. Values near zero score more like a
/// conjunction (coordinate level matching); values near one behave more like a
/// pure disjunction.
#[derive(Debug)]
pub struct LMJelinekMercerSimilarity {
    lambda: f32,
    collection_model: Box<dyn CollectionModel>,
    discount_overlaps: bool,
}

impl LMJelinekMercerSimilarity {
    /// Rejects a `lambda` Java's constructors reject
    /// (`LMJelinekMercerSimilarity.java:47-49`).
    fn check_lambda(lambda: f32) -> Result<()> {
        if lambda.is_nan() || lambda <= 0.0 || lambda > 1.0 {
            return Err(LuceneError::IllegalArgument(
                "lambda must be in the range (0 .. 1]".to_string(),
            ));
        }
        Ok(())
    }

    /// Creates the similarity with the specified *λ* and the default collection
    /// model.
    ///
    /// Equivalent to `new LMJelinekMercerSimilarity(float)`
    /// (`LMJelinekMercerSimilarity.java:62-68`).
    ///
    /// # Errors
    ///
    /// Returns [`LuceneError::IllegalArgument`] when `lambda` is NaN or outside
    /// `(0 .. 1]`.
    pub fn with_lambda(lambda: f32) -> Result<Self> {
        Self::check_lambda(lambda)?;
        Ok(Self {
            lambda,
            collection_model: Box::new(DefaultCollectionModel::new()),
            discount_overlaps: true,
        })
    }

    /// Creates the similarity with the specified collection model and *λ*.
    ///
    /// Equivalent to `new LMJelinekMercerSimilarity(CollectionModel, float)`
    /// (`LMJelinekMercerSimilarity.java:47-49`).
    ///
    /// # Errors
    ///
    /// See [`Self::with_lambda`].
    pub fn with_collection_model_and_lambda(
        collection_model: Box<dyn CollectionModel>,
        lambda: f32,
    ) -> Result<Self> {
        Self::with_parameters(collection_model, true, lambda)
    }

    /// Creates the similarity with every parameter supplied.
    ///
    /// Equivalent to
    /// `new LMJelinekMercerSimilarity(CollectionModel, boolean, float)`
    /// (`LMJelinekMercerSimilarity.java:52-60`).
    ///
    /// # Errors
    ///
    /// See [`Self::with_lambda`].
    pub fn with_parameters(
        collection_model: Box<dyn CollectionModel>,
        discount_overlaps: bool,
        lambda: f32,
    ) -> Result<Self> {
        Self::check_lambda(lambda)?;
        Ok(Self {
            lambda,
            collection_model,
            discount_overlaps,
        })
    }

    /// Returns the *λ* parameter.
    ///
    /// Equivalent to `LMJelinekMercerSimilarity.getLambda()`.
    pub fn lambda(&self) -> f32 {
        self.lambda
    }
}

impl Similarity for LMJelinekMercerSimilarity {
    fn discount_overlaps(&self) -> bool {
        self.discount_overlaps
    }

    fn scorer<'a>(
        &'a self,
        boost: f32,
        collection_stats: &CollectionStatistics,
        term_stats: &[TermStatistics],
    ) -> Box<dyn SimScorer + 'a> {
        similarity_base_scorer(self, boost, collection_stats, term_stats)
    }
}

impl SimilarityBase for LMJelinekMercerSimilarity {
    type Stats = LMStats;

    fn simple_name(&self) -> &'static str {
        "LMJelinekMercerSimilarity"
    }

    fn new_stats(&self, field: &str, boost: f64) -> LMStats {
        lm_new_stats(field, boost)
    }

    fn fill_basic_stats(
        &self,
        stats: &mut LMStats,
        collection_stats: &CollectionStatistics,
        term_stats: &TermStatistics,
    ) {
        lm_fill_basic_stats(
            self.collection_model.as_ref(),
            stats,
            collection_stats,
            term_stats,
        );
    }

    fn score(&self, stats: &LMStats, freq: f64, doc_len: f64) -> f64 {
        // `1 - lambda` is an `int` minus a `float` in Java, so it is computed
        // in `float` and only then widened.
        let one_minus_lambda = f64::from(1.0f32 - self.lambda);
        stats.boost()
            * (1.0
                + (one_minus_lambda * freq / doc_len)
                    / (f64::from(self.lambda) * stats.collection_probability()))
            .ln()
    }

    fn explain_details(
        &self,
        subs: &mut Vec<Explanation>,
        stats: &LMStats,
        freq: f64,
        doc_len: f64,
    ) {
        if stats.boost() != 1.0 {
            subs.push(Explanation::matched(stats.boost() as f32, "boost", vec![]));
        }
        subs.push(Explanation::matched(self.lambda, "lambda", vec![]));
        subs.push(Explanation::matched(
            stats.collection_probability() as f32,
            "P, probability that the current term is generated by the collection",
            vec![],
        ));
        subs.push(Explanation::matched(
            freq as f32,
            "freq, number of occurrences of term in the document",
            vec![],
        ));
        subs.push(Explanation::matched(
            doc_len as f32,
            "dl, length of field",
            vec![],
        ));
        lm_explain_details(self.collection_model.as_ref(), subs, stats);
    }

    /// Overrides the base explanation, as
    /// `LMJelinekMercerSimilarity.explain(BasicStats, Explanation, double)`
    /// does (`LMJelinekMercerSimilarity.java:92-106`).
    fn explain(&self, stats: &LMStats, freq: &Explanation, doc_len: f64) -> Explanation {
        let mut subs = Vec::new();
        let freq_value = freq.value().double_value();
        self.explain_details(&mut subs, stats, freq_value, doc_len);

        Explanation::matched(
            self.score(stats, freq_value, doc_len) as f32,
            format!(
                "score({}, freq={}), computed as boost * log(1 + ((1 - lambda) * freq / dl) /(lambda * P)) from:",
                self.simple_name(),
                freq.value()
            ),
            subs,
        )
    }
}

impl LMSimilarity for LMJelinekMercerSimilarity {
    fn collection_model(&self) -> &dyn CollectionModel {
        self.collection_model.as_ref()
    }

    fn name(&self) -> String {
        format!(
            "Jelinek-Mercer({})",
            java_fmt::format_f(f64::from(self.lambda))
        )
    }
}

impl fmt::Display for LMJelinekMercerSimilarity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&lm_to_string(self))
    }
}

// ---------------------------------------------------------------------------
// IndriDirichletSimilarity
// ---------------------------------------------------------------------------

/// Models `p(w|C)` as the number of occurrences of the term in the collection,
/// divided by the total number of tokens.
///
/// Equivalent to the nested
/// `IndriDirichletSimilarity.IndriCollectionModel`
/// (`IndriDirichletSimilarity.java:107-119`). Note that, despite the Javadoc it
/// inherits, this model does *not* add one to the denominator — unlike
/// [`DefaultCollectionModel`].
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct IndriCollectionModel;

impl IndriCollectionModel {
    /// Creates the parameter-free collection model.
    ///
    /// Equivalent to `new IndriDirichletSimilarity.IndriCollectionModel()`.
    pub fn new() -> Self {
        Self
    }
}

impl CollectionModel for IndriCollectionModel {
    fn compute_probability(&self, stats: &BasicStats) -> f64 {
        stats.total_term_freq() as f64 / stats.number_of_field_tokens() as f64
    }

    fn name(&self) -> Option<String> {
        None
    }
}

/// Bayesian smoothing using Dirichlet priors as implemented in the Indri search
/// engine.
///
/// Equivalent to
/// `org.apache.lucene.search.similarities.IndriDirichletSimilarity`:
///
/// ```text
/// tf_E + mu*P(t|D)   P(t|E) = documentLength + documentMu
/// mu*P(t|C) + tf_D   where   P(t|D) = doclen + mu
/// ```
///
/// A larger `mu` produces more smoothing. Smoothing matters most for short
/// documents, where the probabilities are more granular.
///
/// Note the asymmetry Lucene's constructors have and this port keeps: the
/// no-argument form uses [`IndriCollectionModel`], while the `mu`-only form
/// inherits [`DefaultCollectionModel`] from `LMSimilarity`'s default
/// constructor. Unlike [`LMDirichletSimilarity`], `mu` is not validated.
#[derive(Debug)]
pub struct IndriDirichletSimilarity {
    mu: f32,
    collection_model: Box<dyn CollectionModel>,
    discount_overlaps: bool,
}

impl IndriDirichletSimilarity {
    /// Creates the similarity with the default `mu` of `2000` and the Indri
    /// collection model.
    ///
    /// Equivalent to `new IndriDirichletSimilarity()`
    /// (`IndriDirichletSimilarity.java:63-65`).
    pub fn new() -> Self {
        Self {
            mu: 2000.0,
            collection_model: Box::new(IndriCollectionModel::new()),
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with the provided `mu`.
    ///
    /// Equivalent to `new IndriDirichletSimilarity(float)`
    /// (`IndriDirichletSimilarity.java:53-55`), whose implicit `super()` call
    /// installs [`DefaultCollectionModel`] — not [`IndriCollectionModel`].
    pub fn with_mu(mu: f32) -> Self {
        Self {
            mu,
            collection_model: Box::new(DefaultCollectionModel::new()),
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with the provided collection model and the
    /// default `mu` of `2000`.
    ///
    /// Equivalent to `new IndriDirichletSimilarity(CollectionModel)`
    /// (`IndriDirichletSimilarity.java:58-60`).
    pub fn with_collection_model(collection_model: Box<dyn CollectionModel>) -> Self {
        Self {
            mu: 2000.0,
            collection_model,
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with the provided collection model and `mu`.
    ///
    /// Equivalent to `new IndriDirichletSimilarity(CollectionModel, float)`
    /// (`IndriDirichletSimilarity.java:47-50`).
    pub fn with_collection_model_and_mu(
        collection_model: Box<dyn CollectionModel>,
        mu: f32,
    ) -> Self {
        Self {
            mu,
            collection_model,
            discount_overlaps: true,
        }
    }

    /// Creates the similarity with every parameter supplied.
    ///
    /// Equivalent to
    /// `new IndriDirichletSimilarity(CollectionModel, boolean, float)`
    /// (`IndriDirichletSimilarity.java:41-45`).
    pub fn with_parameters(
        collection_model: Box<dyn CollectionModel>,
        discount_overlaps: bool,
        mu: f32,
    ) -> Self {
        Self {
            mu,
            collection_model,
            discount_overlaps,
        }
    }

    /// Returns the `mu` parameter.
    ///
    /// Equivalent to `IndriDirichletSimilarity.getMu()`.
    pub fn mu(&self) -> f32 {
        self.mu
    }
}

impl Default for IndriDirichletSimilarity {
    fn default() -> Self {
        Self::new()
    }
}

impl Similarity for IndriDirichletSimilarity {
    fn discount_overlaps(&self) -> bool {
        self.discount_overlaps
    }

    fn scorer<'a>(
        &'a self,
        boost: f32,
        collection_stats: &CollectionStatistics,
        term_stats: &[TermStatistics],
    ) -> Box<dyn SimScorer + 'a> {
        similarity_base_scorer(self, boost, collection_stats, term_stats)
    }
}

impl SimilarityBase for IndriDirichletSimilarity {
    type Stats = LMStats;

    fn simple_name(&self) -> &'static str {
        "IndriDirichletSimilarity"
    }

    fn new_stats(&self, field: &str, boost: f64) -> LMStats {
        lm_new_stats(field, boost)
    }

    fn fill_basic_stats(
        &self,
        stats: &mut LMStats,
        collection_stats: &CollectionStatistics,
        term_stats: &TermStatistics,
    ) {
        lm_fill_basic_stats(
            self.collection_model.as_ref(),
            stats,
            collection_stats,
            term_stats,
        );
    }

    fn score(&self, stats: &LMStats, freq: f64, doc_len: f64) -> f64 {
        let mu = f64::from(self.mu);
        let score = (freq + mu * stats.collection_probability()) / (doc_len + mu);
        score.ln()
    }

    fn explain_details(
        &self,
        subs: &mut Vec<Explanation>,
        stats: &LMStats,
        freq: f64,
        doc_len: f64,
    ) {
        if stats.boost() != 1.0 {
            // Java passes the `double` boost unnarrowed here, unlike every
            // other similarity in this package.
            subs.push(Explanation::matched(stats.boost(), "boost", vec![]));
        }

        subs.push(Explanation::matched(self.mu, "mu", vec![]));
        let mu = f64::from(self.mu);
        let collection_probability = stats.collection_probability();
        subs.push(Explanation::matched(
            ((freq + mu * collection_probability) / (doc_len + mu)).ln() as f32,
            "term weight",
            vec![],
        ));
        subs.push(Explanation::matched(
            (mu / (doc_len + mu)).ln() as f32,
            "document norm",
            vec![],
        ));
        lm_explain_details(self.collection_model.as_ref(), subs, stats);
    }
}

impl LMSimilarity for IndriDirichletSimilarity {
    fn collection_model(&self) -> &dyn CollectionModel {
        self.collection_model.as_ref()
    }

    fn name(&self) -> String {
        format!("IndriDirichlet({})", java_fmt::format_f(f64::from(self.mu)))
    }
}

impl fmt::Display for IndriDirichletSimilarity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&lm_to_string(self))
    }
}
